DROP TABLE IF EXISTS `team`;
CREATE TABLE `team` (
	shop_entry_code int default 0,
	shop_code int default 0,
	medianet_id int default 0,
	track_code varchar(30) default null,
	text varchar(30) default null,
	club_full_name varchar(30) default null,
	url_prod varchar(30) default null,
	team_id int default 0 primary key,
	postal_code varchar(11) default 0,
	timezone varchar(30) default null,
	club_common_url varchar(30) default null,
	esp_common_url varchar(30) default null,
	url_esp varchar(30) default null,
	tertiary varchar(30) default null,
	esp_common_name varchar(30) default null,
	primary_link varchar(30) default null,
	display_code varchar(30) default null,
	newsletter_group_id int default 0,
	team_code varchar(30) default null,
	club_id int default 0,
	id int default 0,
	field varchar(100) default null,
	club_common_name varchar(30) default null,
	location varchar(30) default null,
	city varchar(30) default null,
	division varchar(30) default null,
	name_display_long varchar(100) default null,
	club varchar(30) default null,
	track_filter varchar(30) default null,
	`primary` varchar(30) default null,
	es_track_code varchar(30) default null,
	newsletter_category_id varchar(30) default null,
	address varchar(30) default null,
	club_spanish_name varchar(100) default null,
	secondary varchar(30) default null,
	state_province varchar(30) default null,
	league varchar(30) default null,
	phone varchar(30) default null,
	country varchar(30) default null,
	name_display_short varchar(30) default null,
	url_cache varchar(30) default null,
	historical_team_code varchar(30) default null,
	pressbox_url varchar(100) default null
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `player`;
CREATE TABLE `player` (
	name_matrilineal varchar(50) default null,
	h3b int default 0,
	death_city varchar(50) default null,
	ab int default 0,
	name_first varchar(50) default null,
	weight int default 0,
	status_code varchar(3) default null,
	active_sw enum('Y', 'N'),
	ao int default 0,
	tb int default 0,
	primary_position char(1) default null,
	go int default 0,
	team_id int default 0,
	death_state varchar(50) default null,
	bats enum('R', 'L', 'S'),
	birth_country varchar(50) default null,
	name_display_last_first_html varchar(50) default null,
	player_id int not null primary key,
	team_name varchar(50) default null,
	avg double default 0,
	team_code varchar(3) default null,
	birth_city varchar(50) default null,
	name_display_roster varchar(50) default null,
	death_country varchar(50) default null,
	hbp int default 0,
	birth_state varchar(50) default null,
	name_middle varchar(50) default null,
	pro_debut_date datetime default null,
	h int default 0,
	name_display_first_last_html varchar(50) default null,
	name_prefix varchar(50) default null,
	high_school varchar(100) default null,
	name_use varchar(50) default null,
	cs int default 0,
	status varchar(50) default null,
	name_nick varchar(50) default null,
	throws enum('R', 'L'),
	name_display_roster_html varchar(50) default null,
	end_date datetime default null,
	ops double default 0,
	hr int default 0,
	height_inches int default 0,
	name_full varchar(50) default null,
	primary_sport_code varchar(10) default null,
	sb int default 0,
	r int default 0,
	go_ao double default 0,
	file_code varchar(10) default null,
	status_date datetime default null,
	height_feet int default 0,
	name_last varchar(50) default null,
	g int default 0,
	gender enum('M', 'F'),
	ibb int default 0,
	death_date datetime default null,
	name_title varchar(50) default null,
	name_display_last_first varchar(50) default null,
	start_date datetime default null,
	bb int default 0,
	team_abbrev varchar(3) default null,
	name_display_first_last varchar(50) default null,
	so int default 0,
	rbi int default 0,
	primary_position_txt varchar(2) default null,
	birth_date datetime default null,
	college varchar(100) default null,
	slg double default null,
	jersey_number int default null,
	obp double default null,
	h2b int default 0,
	np int default 0,
	ir int default 0,
	cg int default 0,
	w int default 0,
	l int default 0,
	s int default 0,
	er int default 0,
	sho int default 0,
	era double default 0,
	sv int default 0,
	svo int default 0,
	wp int default 0,
	gs int default 0,
	whip double default 0,
	irs int default 0,
	ip double default 0,
	hb int default 0,
	tbf int default 0,
	bk int default 0,
	gidp int default 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;

DROP TABLE IF EXISTS `log_batter`;
CREATE TABLE `log_batter`(
	player_id int default 0,
	game_id varchar(100) default '',
	game_date date,
	game_type char(1) default '',
	`date` varchar(35) default '',
	game_pk int default null,
	opp varchar(3) default '',
	opp_team_id int default 0,
	opp_team_display_full varchar(35) default '',
	opp_team_display_short varchar(35) default '',
	home_away enum('H', 'A'),
	bb int default 0,
	hr int default 0,
	ibb int default 0,
	cs int default 0,
	go_ao double default 0,
	hbp int default 0,
	tb int default 0,
	h3b int default 0,
	ab int default 0,
	h int default 0,
	ao int default 0,
	r int default 0,
	rbi int default 0,
	go int default 0,
	slg double default 0,
	obp double default 0,
	ops double default 0,
	so int default 0,
	sb int default 0,
	avg double default 0,
	h2b int default 0,
	PRIMARY KEY (game_id, player_id)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `log_pitcher`;
CREATE TABLE `log_pitcher`(
	player_id int default 0,
	game_id varchar(100) default '',
	game_date date,
	game_type char(1) default '',
	`date` varchar(35) default '',
	game_pk int default null,
	opp varchar(3) default '',
	opp_team_id int default 0,
	opp_team_display_full varchar(35) default '',
	opp_team_display_short varchar(35) default '',
	home_away enum('H', 'A'),
	bb int default 0,
	hr int default 0,
	ibb int default 0,
	wp int default 0,
	bk int default 0,
	era double default 0,
	hb int default 0,
	go_ao double default 0,
	gidp int default 0,
	h int default 0,
	np int default 0,
	sho int default 0,
	irs int default 0,
	svo int default 0,
	ab int default 0,
	gs int default 0,
	g int default 0,
	ip double default 0,
	ir int default 0,
	cg int default 0,
	l int default 0,
	ao int default 0,
	s int default 0,
	r int default 0,
	w int default 0,
	go int default 0,
	whip double default 0,
	er int default 0,
	sv int default 0,
	so int default 0,
	avg double default 0,
	tbf int default 0,
	PRIMARY KEY (game_id, player_id)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `schedule`;
CREATE TABLE `schedule` (
	game_id varchar(100) default '' primary key,
	game_date date,
	game_pk int,
	game_time_is_tbd tinyint(1),
	game_venue varchar(100) default '',
	game_time bigint,
	game_time_offset_eastern int,
	game_location varchar(100) default '',
	division_id int,
	game_time_offset_local int,
	scheduledTime bigint,
	game_status char(1),
	mlbtv tinyint(1),
	is_suspension_resumption tinyint(1),
	video_uri varchar(255) default '',
	sport_code varchar(10) default '',
	venue_id int,
	wrapup varchar(1000) default '',
	preview varchar(1000) default '',
	game_type char(1),
	resumptionTime bigint,
	game_dh varchar(5) default null,
	game_num int,
	home_team_id int,
	home_team_full varchar(30) default '',
	home_team_display_code varchar(5) default '',
	home_probable_id int,
	home_score int default null,
	away_team_id int,
	away_team_full varchar(30) default '',
	away_team_display_code char(3) default '',
	away_probable_id int,
	away_score int default null
) ENGINE = InnoDB;

DROP TABLE IF EXISTS transaction;
CREATE TABLE transaction (
	conditional_sw varchar(30) default null,
	effective_date date default null,
	final_asset varchar(100) default null,
	final_asset_type varchar(100) default null,
	from_team varchar(100) default null,
	from_team_id int default null,
	name_display_first_last varchar(100) default null,
	name_display_last_first varchar(100) default null,
	name_sort varchar(100) default null,
	note varchar(1000) default null,
	orig_asset varchar(100) default null,
	orig_asset_type varchar(100) default null,
	player varchar(100) default null,
	player_id int default null,
	resolution_cd varchar(100) default null,
	resolution_date date default null,
	team varchar(100) default null,
	team_id int default null,
	trans_date date default null,
	trans_date_cd varchar(10) default null,
	transaction_id int not null primary key,
	type varchar(100) default null,
	type_cd varchar(100) default null
) ENGINE = InnoDB DEFAULT CHARSET = utf8 COLLATE = utf8_bin;
